### ISSUE TITLE
About the training code release and training step reproduce.

### ISSUE THREAD

**Issue by secondlevel** [prasunroy/tips#1]
Hello, 

I want to know if the training code has been released? 
Thank you very much.

**Comment by prasunroy** [comment]
Hi, thank you for your interest in this work.

The complete code for stage-3 is available in a separate repository https://github.com/prasunroy/pose-transfer.
Our stage-1 is based on a modified version of the above codebase, followed by a fully-connected network in stage-2.

For clarity, we plan to integrate everything with some additional codes under this repository soon.

**Comment by secondlevel** [comment]
OK, thanks. This is very helpful.

**Comment by prasunroy** [comment]
Completed with commit [414242a](https://github.com/prasunroy/tips/commit/414242abdbf5a906058679bcf2fd62f968263cdd).
